userdive/agent.js

.gitignore, README.md, package.json, webpack.config.js
=> chore(README) update License

LICENSE
=> fix(LICENSE) use GPLv3

src/browser.js, src/store.js, src/types.js
=> chore(src) update required params

package.json, yarn.lock
=> chore(package) add build env

src/core.js, src/requests.js, test/core.test.js
cache clear when polling fixedness
=> fix(src) clear polling cache

.travis.yml, package.json
=> Deploy cdn when tag pushes too

package.json
=> chore(package): update karma-webpack to version 2.0.3

.travis.yml
=> Fix wrong deployment task and deploy only karma tests are passed.

.travis.yml
- Deploy agent.js to domain root.
- Add task to deploy to the staging.
=> Fix deploy path and add deployment task for staging

package.json
=> chore(package): update raven-js to version 3.16.0

src/constants.js
=> Revert "chore(src) update interval time"

.travis.yml, package.json, src/constants.js, src/core.js, test/constants.test.js, test/core.test.js
=> chore(src) update cache time

src/core.js, src/events/scroll.js
=> fix(src) change device size api

src/constants.js, src/core.js
remove Infinite transmission 😢
=> fix(src) fix send condition

package.json, src/core.js, yarn.lock
=> chore(package): update dependencies

package.json, src/events/touch.js, test/events.touch.test.js
=> chore(src/events) add tap filter

src/core.js, src/requests.js, test/agent.test.js, test/core.test.js, test/global.test.js
Closes #105 
`img.onerror` can't handle HTTP status code.
So, just stop agent.js if error raised.
=> Feature handle request error

README.md, src/agent.js, src/core.js, test/core.test.js
=> fix(src) update force unbind

README.md, package.json, src/core.js, src/requests.js, test/core.test.js, test/requests.test.js
=> fix(src) remove all old listeners

package.json
=> Revert "Update auto-cookie to the latest version 🚀"

src/agent.ts, src/core.ts, src/events.ts, src/events/click.ts, src/events/mousemove.ts, src/events/scroll.ts, src/events/touch.ts, src/logger.ts, src/store.ts, test/core.test.ts, test/store.test.ts
- add class field scope
- remove `_*` namespace
=> refacor(src) add private scope 

src/requests.ts, src/store.ts, test/requests.test.ts
=> fix(src) fix create queries

karma.conf.ts, package.json, src/core.ts, test/core.test.ts, yarn.lock
Closes #154 
```js
// equal _ud('send', 'pageview', location.href)
_ud('send', 'pageview', location.pathname) 
```
espower
=> chore(src) allow pathname pageview

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> feat(.github) add templates

src/agent.ts, src/browser.ts, src/core.ts, src/entrypoint/debug.ts, src/events.ts, src/events/click.ts, src/events/mousemove.ts, src/events/scroll.ts, src/events/touch.ts, test/agent.test.ts, test/constants.test.ts, test/core.test.ts, test/events.click.test.ts, test/events.mousemove.test.ts, test/events.test.ts, test/events.touch.test.ts, test/global.test.ts, test/logger.test.ts, test/requests.test.ts, test/store.test.ts
Connect to https://github.com/uncovertruth/tslint-config/pull/28
=> refactor(src|test) --fix ordered-import

yarn.lock
release v0.10.0 !!!!11 
https://github.com/userdive/agent.js/compare/v0.9.2...release?w=1&ts=2
=> chore(yarn.lock) update

README.md
=> docs(readme) Added simple usage

README.md
=> add plugin usage

.eslintrc.json, README.md, package.json
=> docs(readme) fix typo

package.json, yarn.lock
=> chore(package) Added size-limit

.travis.yml
=> chore(package) Added build size check

README.md, package.json
https://github.com/userdive/agent.js/compare/v0.10.0...release
=> chore(package) set v0.11.0

.gitignore, .travis.yml, README.md, lerna.json, package.json, packages/agent/.yarnclean, packages/agent/README.md, packages/agent/karma.conf.ts, packages/agent/package.json, packages/agent/tsconfig.json, tsconfig.json, webpack.config.ts, yarn.lock
=> refactor(package) Added linter to PROJECT_ROOT

lerna.json, package.json, packages/agent/package.json, packages/agent/src/core.ts, packages/agent/src/logger.ts, packages/agent/src/store.ts, packages/agent/test/store.test.ts, webpack.config.ts
=> fix(packages/agent) cleanup send custom variables 

package.json
=> fix(package) remove unused cdn files

.travis.yml, examples/simple/package.json, examples/with-google-tag-manager/package.json, package.json, packages/agent/package.json, scripts/publish, yarn.lock
=> Fixed publish

examples/simple/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-google-tag-manager/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, website/package.json
https://github.com/userdive/agent.js/compare/v0.11.0...release
=> Release v0.12.0

.travis.yml
Skip sauce tests if `dependabot` branch
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
=> chore(travis) Added workflow

.gitignore, CHANGELOG.md, examples/linker/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, lerna.json, package.json, packages/agent/package.json, packages/linker/package.json, website/package.json, yarn.lock
=> Release v0.13.0

.travis.yml, README.md, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, package.json, packages/linker/package.json, packages/userdive/LICENSE, packages/userdive/README.md, packages/userdive/karma.conf.ts, packages/userdive/package.json, packages/userdive/src/index.ts, packages/userdive/test/index.test.ts, packages/userdive/tsconfig.json, yarn.lock
=> feat(packages) Merge userdive.js

.travis.yml
=> refactor(travis) skip sauce when push

examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/linker/package.json, packages/userdive/package.json, website/package.json
=> chore(package) set v0.14.0-beta1

.travis.yml, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, package.json, packages/agent/package.json, packages/agent/src/agent.ts, packages/agent/src/constants.ts, packages/agent/src/core.ts, packages/agent/src/entrypoint/debug.ts, packages/agent/src/events.ts, packages/agent/src/requests.ts, packages/agent/src/store.ts, packages/agent/src/types.ts, packages/agent/test/agent.test.ts, packages/agent/test/core.test.ts, packages/agent/test/global.test.ts, packages/linker/package.json, packages/linker/src/handler.ts, packages/linker/src/linker.ts, packages/linker/test/handler.test.ts, packages/linker/test/linker.test.ts, packages/userdive/package.json, tsconfig.json, website/package.json, yarn.lock
=> Fixed linker lifecycle

examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, package.json, packages/agent/package.json, packages/agent/src/agent.ts, packages/agent/test/agent.test.ts, packages/linker/package.json, packages/linker/src/linker.ts, packages/userdive/package.json, website/package.json, yarn.lock
Oops, sorry.
Must to be core private
=> fix(packages/agent) fix core scope 

examples/with-angular/tsconfig.json, examples/with-angular1/tsconfig.json, examples/with-react/tsconfig.json, examples/with-vue/tsconfig.json
=> refactor(examples) use es2015

renovate.json
=> fix(renovate) Added examples

README.md, appveyor.yml, karma.conf.base.ts, package.json, yarn.lock
=> feat(appveyor) Actiate

.textlintrc.js, CHANGELOG.md, LICENSE, README.md, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, lint-staged.config.js, package.json, packages/agent/README.md, packages/agent/package.json, packages/linker/README.md, packages/linker/package.json, packages/userdive/README.md, packages/userdive/package.json, website/package.json
https://github.com/userdive/agent.js/compare/v0.13.0...release
=> Release v0.14.0

scripts/publish
```
lerna info version 2.9.0
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! you must verify your email before publishing a new package: https://www.npmjs.com/email-edit : @[secure]/linker
```
=> fix(scripts) Added author

.travis.yml
=> add developers site

.circleci/config.yml, examples/package.json, examples/spa-base.test.ts, examples/with-angular/index.pug, examples/with-angular/with-angular.test.ts, examples/with-angular1/index.pug, examples/with-angular1/with-angular1.test.ts, examples/with-react/components/Sample.tsx, examples/with-react/components/sample1.tsx, examples/with-react/components/sample2.tsx, examples/with-react/index.pug, examples/with-react/pages/index.tsx, examples/with-react/pages/with-react.test.ts, examples/with-vue/with-vue.test.ts
Connect to #301 
Fix e2e test for examples at Circleci.
=> Fix e2e test

lint-staged.config.js, packages/userdive/karma.conf.ts, packages/userdive/src/index.ts, packages/userdive/test/index.test.ts
=> refactor(packages/userdive) export namespace

CHANGELOG.md, examples/package.json, examples/simple/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/linker/package.json, packages/userdive/package.json, website/package.json
Release v0.15.0
https://github.com/userdive/agent.js/compare/v0.14.0...release
=> Release v0.15.0

README.md, examples/linker/linker.pug, packages/linker/README.md
=> add linker usage and badge to README. And tweak example.

examples/built-in/package.json, examples/linker/package.json, examples/package.json, examples/with-react/package.json, lerna.json, packages/agent/package.json, packages/agent/src/global.ts, packages/linker/package.json, website/package.json
=> Release v1.0.0-beta1

examples/built-in/package.json, examples/linker/package.json, examples/package.json, examples/with-react/package.json, lerna.json, packages/agent/package.json, packages/agent/src/agent.ts, packages/agent/src/constants.ts, packages/agent/src/core.ts, packages/agent/src/entrypoint/debug.ts, packages/agent/src/global.ts, packages/agent/src/logger.ts, packages/agent/src/types.ts, packages/agent/test/global.test.ts, packages/agent/test/logger.test.ts, packages/linker/package.json, website/package.json
=>  fix(packages/agent) create queue first 

examples/index.pug
Closes #382
bootstrap3のままとりあえず構造など直しました。
その他に何をしたらいいのかちょっとわからなかったので一旦見た目のみプッシュします。
=> Re design example froms

website/core/Footer.js, website/siteConfig.js
Added Google tag managor
refs https://github.com/facebook/Docusaurus/blob/508090377eb14f27db5ccb87c5fbe70ab79dc62d/lib/core/Site.js#L90-L104
=> chore(website) insert Google Tag manager

docs/event.md, examples/built-in/package.json, examples/linker/package.json, examples/package.json, examples/with-react/package.json, lerna.json, package.json, packages/agent/README.md, packages/agent/package.json, packages/agent/src/agent.ts, packages/agent/src/constants.ts, packages/agent/src/core.ts, packages/agent/src/global.ts, packages/agent/src/types.ts, packages/agent/test/core.test.ts, packages/linker/package.json, website/i18n/en.json, website/package.json, website/sidebars.json
=> send event

.circleci/config.yml, packages/agent/package.json, packages/agent/src/agent.ts, packages/agent/src/constants.ts, packages/agent/src/core.ts, packages/agent/src/types.ts, packages/agent/test/agent.test.ts, packages/agent/test/core.test.ts, packages/linker/src/provide.ts, packages/userdive/src/index.ts, packages/userdive/src/types.ts, tsconfig.json
Closes #402 
refs; https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google.analytics/index.d.ts
=> fix(packages) Added global entrypoint type

website/static/css/custom.css
Closes #406
logoやメインセクションのlogo画像など勝手にnoneになる仕様を上書き。
その他にも細かい調整をしました。
=> fix(website) header logos

.circleci/config.yml, .travis.yml, crowdin.yaml, package.json, website/languages.js
=> Run e2e cron test

packages/agent/src/agent.ts, packages/agent/src/global.ts
Connect to https://github.com/userdive/agent.js/pull/407/files#r177038118
```js
_ud("create", 'id', {
auto: true,
});
_ud("send", "pageview");
```
=> fix(packages/agent) fix send pageview default

.circleci/config.yml, package.json
https://circleci.com/gh/userdive/agent.js/278
=> fix(circleci) fix deploy task

.circleci/config.yml, examples/built-in/package.json, examples/linker/package.json, examples/package.json, examples/simple/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/agent/src/entrypoint/debug.ts, packages/agent/src/entrypoint/index.ts, packages/agent/src/global.ts, packages/agent/test/agent.test.ts, packages/agent/test/global.test.ts, packages/linker/package.json, packages/userdive/package.json, website/package.json
Closes https://github.com/userdive/agent.js/issues/431
Connect to https://github.com/userdive/agent.js/pull/425/files#diff-363bc5c09c492691317051835a9df4b0R28
=> fix(packages/agent) fix v0.x auto options

packages/userdive/src/index.ts
=> refactor(packages/userdive) cached namespace

examples/README.md, examples/index.pug, renovate.json
=> fix(examples) update example link

package.json, packages/agent/README.md, packages/linker/README.md, packages/userdive/README.md
=> fix(package) ci skip when deploy examples

examples/index.pug, examples/simple/cd-with-send.pug, examples/simple/cd-with-set.pug
connect to #501 
1. checkout this PR.
1. run `yarn install` && `npm start`
1. access to [send example](http://localhost:8080/simple/cd-with-send.html) and [set example](http://localhost:8080/simple/cd-with-set.html)
1. check send params
=> add custom dimension example

docs/command-queue.md, docs/field-reference.md
=> tweak document

.circleci/config.yml, .dockerignore, Dockerfile, examples/nightwatch.json, examples/package.json, yarn.lock
- add Dockerfile
- change test runner image for e2e
=> add e2e test runtime

.travis.yml, browser-providers.conf.ts
reduce saucelabs connect fail.
=> reduce sauce device in ci

Dockerfile
Google Chrome version was updated
=> Update Google Chrome version

examples/nightwatch.json
nightwatch configuration spcified selenium version.
=> update selenium-server using nightwatch

Dockerfile
Using latest or stable version.
=> remove unnecessary specified version in Dockerfile

package.json, packages/kaizenplatform/README.md, packages/kaizenplatform/package.json, packages/kaizenplatform/src/index.ts, packages/kaizenplatform/src/plugin.ts, packages/kaizenplatform/test/index.test.ts, packages/kaizenplatform/test/kzs.test.ts, packages/kaizenplatform/tsconfig.json, packages/provider/README.md, packages/userdive/src/types.ts, webpack.config.ts
=> feat(packages/kaizenplatform) Added integration 

.textlintrc.js
*   npm run lint
*   [ ] pass all linter
=> ignore domains not mandatory service from no-dead-link lint

docs/linker-plugin.md, website/i18n/en.json, website/sidebars.json
add linker (cross-domain) reference. only English.
*   npm start
*   access to [new document](http://localhost:3000/docs/en/linker-plugin.html)
*   [ ] check english expression
*   [ ] check link
=> add linker docs

examples/index.pug, examples/kaizen-platform/README.md, examples/kaizen-platform/index.pug, examples/kaizen-platform/package.json, examples/plugin-linker/README.md, examples/simple/README.md, examples/with-angular/README.md, examples/with-angular1/README.md, examples/with-google-tag-manager/README.md, examples/with-react/README.md, examples/with-vue/README.md
Closes #583
*   yarn start
*   access to http://localhost:8080/agent.js/kaizen-platform/
*   [ ] load KaizenPlatform script
*   [ ] load integration plugin
*   [ ] load agent.js and works
*   [ ] check README via all example pages
=> add kaizenplatform integration example

karma.conf.ts
karma config tune up for saucelabs CI.
=> tuning for saucelabs CI

CHANGELOG.md, README.md
- lerna-changelog not worked from v1.0.0 release
- update root document
=> fix v1.1.0 release docs

.circleci/config.yml, Dockerfile, examples/package.json
=> add chrome symbolik link

examples/index.pug, examples/simple/page.pug, examples/test/tracker/page.test.ts
=> add location override example

README.md, packages/vwo/package.json
=> Remove private

CHANGELOG.md, README.md, examples/built-in/package.json, examples/kaizen-platform/package.json, examples/package.json, examples/simple/package.json, examples/vwo/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/kaizenplatform/package.json, packages/linker/package.json, packages/provider/package.json, packages/vwo/package.json, website/package.json
https://github.com/userdive/agent.js/compare/v1.1.0...master
=> bump up to v1.12.0

examples/index.pug, examples/simple/cd-with-send.pug, examples/simple/cd-with-set.pug, examples/simple/events.pug, examples/simple/index.pug, examples/simple/multiple.pug, examples/with-angular/index.pug, examples/with-angular1/index.pug, examples/with-react/index.pug, examples/with-vue/index.pug
fix link grouping and bread crumb
=> fix link group

.travis.yml
skip karma test with sauclelabs when not change code.
=> add skip ci for sauce

examples/index.pug, examples/simple/cd-with-send.pug, examples/simple/cd-with-set.pug, examples/simple/events.pug, examples/simple/index.pug, examples/simple/multiple.pug, examples/with-angular/index.pug, examples/with-angular1/index.pug, examples/with-react/index.pug, examples/with-vue/index.pug
=> list toggle化 

.travis.yml, karma.conf.ts
Refactor tests its fail sometimes.
=> Run test in parallel

.travis.yml, examples/google-optimize/README.md, examples/index.pug, examples/test/google-optimize-deploy.test.ts, examples/test/google-optimize-local.test.ts, examples/test/tracker/google-optimize.test.ts
*   Checking each CI results
*   [ ] passed CI
=> publish google optimize example

examples/index.pug, examples/optimizely-x/README.md, examples/optimizely-x/index.pug, examples/optimizely-x/package.json
Connect to #711 
*   run npm start
*   [ ] access to [example page](http://localhost:8080/agent.js/optimizely-x/) and check contents
note: using GTM (container ID: **GTM-MPWXB3**)
=> add optimizely x example page

examples/with-google-tag-manager/index.pug
=> fix gtm container ID

examples/built-in/package.json, examples/package.json, examples/with-google-tag-manager/package.json, examples/with-react/package.json, lerna.json, packages/kaizenplatform/package.json, packages/linker/package.json, packages/vwo/package.json, website/package.json, yarn.lock
- upgrade webpack v4
- fix vwo plugin bug
https://github.com/userdive/agent.js/compare/v1.2.0...master
This version include PR described below;
- apply webpack v4 (#717 )
- vwo plugin bugfix (#724 )
=> bump up to v1.2.1

packages/optimizely_x/README.md, packages/optimizely_x/package.json, packages/optimizely_x/src/index.ts, packages/optimizely_x/src/plugin.ts, packages/optimizely_x/test/index.test.ts, packages/optimizely_x/test/optimizely-x.test.ts, packages/optimizely_x/tsconfig.json
Connect to #711 
*   yarn test
*   [ ] pass all tests
=> add optimizely x plugin

.size-limit.js, webpack.config.ts
fix optimizely packing
*   [ ] build optimizely-x-plugin.js
=> add optimizely packing

.travis.yml
*   Check Travis CI.
*  do not run cross-browser stage on push CI
*  run cross-browser stage on pr CI
=> use cross-browser stage

packages/vwo/src/plugin.ts, packages/vwo/test/vwo.test.ts
VWO can create experience in **SAME** URL
The plugin should be able to send events for it.
Closes #763 
*   read code diff
*   [ ] pass test
=> support multiple AB testing

examples/test/google-optimize-deploy.test.ts, examples/test/google-optimize-local.test.ts, examples/test/kaizen-platform-gtm.test.ts, examples/test/kaizen-platform.test.ts, examples/test/optimizely-x-gtm.test.ts, examples/test/optimizely-x.test.ts, examples/test/test-util.ts, examples/test/tracker/optimizely-x-gtm.test.ts, examples/test/tracker/vwo-gtm.test.ts, examples/test/vwo-gtm.test.ts, examples/test/vwo.test.ts
Closes #763 
*   yarn start
*   after raise local server, execute `yarn e2e` on another console.
*   [ ] passed e2e test at local
*   [ ] passed e2e test at Circle CI
=> e2e tracker test should check multiple events

packages/agent/src/constants.ts
Closes #851 
this is hot fix patch
=> set initial cookiePath

.size-limit.js, examples/built-in/package.json, examples/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/agent/src/constants.ts, packages/kaizenplatform/package.json, packages/linker/package.json, packages/optimizely_x/package.json, packages/provider/package.json, packages/vwo/package.json, website/package.json
This version FIXED that unexpected session missing
- change cookie name to `_ud` from `_ud2`
=> bump up to v2.0.0

docs/events.md
Check diff and expressions.
*   yarn install
*   yarn start
*  look event tracking page. [url](http://localhost:3000/docs/en/events.html)
*   [x] Applied added sentences.
=> tweak event send API doc

examples/index.pug, examples/plugin-linker/area.pug, examples/plugin-linker/index.pug, packages/linker/src/handler.ts, packages/linker/test/handler.test.ts
Linker plugin support area tag newly.
Closes #893 
*   yarn run test
*   [x] No error
=> feature(@userdive/linker) support area-tag 

.size-limit.js, examples/index.pug, examples/plugin-linker/linker-with-gtm.pug, packages/agent/package.json, packages/agent/src/events.ts, packages/agent/src/events/click.ts, packages/agent/src/events/mousemove.ts, packages/agent/src/events/scroll.ts, packages/agent/src/events/touch.ts, packages/agent/test/core.test.ts, packages/agent/test/events.test.ts, packages/kaizenplatform/package.json, packages/linker/package.json, packages/optimizely_x/package.json, packages/provider/package.json, packages/userdive/package.json, packages/vwo/package.json, yarn.lock
Connect to #914
*   [ ] plz check global raw data 🙏
=> [breaking changes] Dispatch only tap event, exclude touchmove

.size-limit.js, browser-providers.conf.ts, packages/agent/src/constants.ts
Upgrade client version to 2 (backward incompatible changes)
*
*   [ ]
=> Change client version

.size-limit.js, browser-providers.conf.ts, packages/agent/package.json, packages/agent/src/constants.ts, packages/agent/src/events/touch.ts, packages/kaizenplatform/package.json, packages/linker/package.json, packages/optimizely_x/package.json, packages/provider/package.json, packages/userdive/package.json, packages/vwo/package.json
- This is backward incompatible changes
- Set client version to 2
*
*   [ ]
=> Replace touch action (only tap)

packages/agent/src/agent.ts, packages/agent/src/core.ts, packages/agent/test/core.test.ts
- Closes #937 
- Send latest interactions on 'pagehide' forcely
* Send last event when move page
*   [ ]
=> Send interactions on pagehide forcely

packages/agent/src/constants.ts, packages/agent/src/core.ts, packages/agent/src/types.ts, packages/agent/test/agent.test.ts, packages/agent/test/core.test.ts
=> Rename to interactions

.size-limit.js, packages/agent/src/core.ts, packages/agent/test/core.test.ts
interaction  should be send version as query string.
deploy and check interaction request.
*   [ ] passed CI
=> send interaction with version param

CHANGELOG.md, examples/built-in/package.json, examples/google-optimize/package.json, examples/kaizen-platform/package.json, examples/optimizely-x/package.json, examples/package.json, examples/plugin-create/package.json, examples/plugin-linker/package.json, examples/simple/package.json, examples/vwo/package.json, examples/with-angular/package.json, examples/with-angular1/package.json, examples/with-google-tag-manager/package.json, examples/with-react/package.json, examples/with-vue/package.json, lerna.json, packages/agent/package.json, packages/kaizenplatform/package.json, packages/linker/package.json, packages/optimizely_x/package.json, packages/provider/package.json, packages/userdive/package.json, packages/vwo/package.json, website/package.json
=> Release 3.0.0
